language: ruby
sudo: false
cache: bundler

before_install:
  - gem install bundler
install:
  - bundle update

script: 'RUBYOPT=-rubygems rake bacon'
before_script:
  - test -s "$HOME/.rvm/scripts/rvm" && source "$HOME/.rvm/scripts/rvm"
  - test -s .gems && rvm gemset import .gems
rvm:
  - 1.8.7
  - 1.9.3
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
  - rbx-3
  - jruby-9.2.9.0
  - jruby-head
  - 2.2.10
  - 2.3.8
  - 2.4.9
  - 2.5.7
  - 2.6.5
  - 2.7.0
  - ruby-head
notifications:
  email:
#    - mf@rubyists.com
    - aldentea-dev@telepathy.aldentea.0g0.jp
branches:
  only:
#    - master
    - develop
matrix:
  allow_failures:
    - rvm: 1.8.7
    - rvm: 1.9.3
    - rvm: jruby-18mode
    - rvm: jruby-19mode
    - rvm: rbx-18mode
    - rvm: rbx-19mode
    - rvm: 2.2.10
    - rvm: 2.3.8
    - rvm: 2.4.9 